### ISSUE TITLE
Exception while sql insertion query

### ISSUE THREAD

**Issue by anushyakkutty** [MathewManu/MovieMon#8]
Exception while running queryINSERT INTO MOVIE (FILENAME, FILELOCATION, TITLE, Y
EAR, IMDBRATING, IMDBID, GENRE) VALUES (  'Theres.Something.About.Mary.EXTENDED.
CUT.1998.720p.BrRip.x264.YIFY.mp4','c:\Anushya\movies_manu\aug_20\Theres Somethi
ng About Mary EXTENDED (1998)\Theres.Something.About.Mary.EXTENDED.CUT.1998.720p
.BrRip.x264.YIFY.mp4','There's Something About Mary','1998','7.1','tt0129387','C
omedy, Romance' ); Exception : unexpected token: S required: )
ERROR: insert error

**Comment by MathewManu** [comment]
i don't have this file.. can you check if this file is getting inserted properly after preparestatement fix ?

**Comment by MathewManu** [comment]
@anushyakkutty Please verify this..

**Comment by MathewManu** [comment]
not facing any issues.
